// Re-exported from @trip/ui shared component package
export {
  FormInput,
  FormTextarea,
  IconWrapper,
  IconButton,
  StatCard,
  type StatCardTone,
  SectionHeader,
  FooterActionBar,
  DashedAddButton,
  StatsSummary,
  EmptyState,
  Pagination,
  ConfirmDialog,
  ToggleSwitch,
  LoadingState,
  ErrorState,
  Banner,
  Modal,
  FilterTabs,
  ToastProvider,
  useToast,
  StatusBadge,
  type StatusConfig,
  type StatusTone,
  Skeleton,
  CardSkeleton,
  TableRowSkeleton,
  StatCardSkeleton,
  PageSkeleton,
  // Migrated admin-specific components
  AgreementModal,
  AuthHero,
  ChangeSummaryModal,
  type ChangeEntry,
  ChannelBadge,
  type FollowChannel,
  DatePicker,
  DevAutoFill,
  MobilePreview,
  PreviewDrawer,
  QRCodeDisplay,
  SegmentedControl,
  SelectPicker,
  type SelectOption,
  TimePicker,
  TripDayMap,
  type MapActivity,
  TripDayMapLazy,
} from "@trip/ui";

// Local-only admin components (depend on @/lib/*)
export { AuthGuard } from "./auth-guard";
export { MediaLibraryModal } from "./media-library-modal";
export { RemoteLegalContent } from "./remote-legal-content";
export { ImageUpload } from "./image-upload";
