export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  myTrips: "/dashboard/my-trips",
  profile: "/dashboard/profile",
  usage: "/dashboard/usage",
  upgrade: "/dashboard/upgrade",
  billing: "/dashboard/billing",
  help: "/dashboard/help",
  terms: "/dashboard/terms",
  privacy: "/dashboard/privacy",
  tripNew: "/dashboard/trips/new",
  tripEdit: (id: string) => `/dashboard/trips/${id}/edit` as const,
  tripPreview: (id: string) => `/dashboard/trips/${id}/preview` as const,
  tripPublish: (id: string) => `/dashboard/trips/${id}/publish` as const,
  tripManage: (id: string) => `/dashboard/trips/${id}/manage` as const,
  tripReceipts: (id: string) => `/dashboard/trips/${id}/receipts` as const,
} as const;
